// Throwaway demo for issue #195 (dynamic OpenRouter model picker). Fixture
// data only, illustrating row layout for design review — delete once the
// real picker lands in cmd/clown/profileform.go.
package main

import (
	"fmt"
	"os"
	"regexp"
	"strings"

	"github.com/charmbracelet/bubbles/list"
	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
)

type modelItem struct {
	id         string
	contextLen string
	pricing    string
	shortDesc  string // markdown/entity-cleaned, capped ~72 chars — the list row
	fullDesc   string // same cleaning, untruncated — the detail-pane preview
}

func (m modelItem) Title() string {
	return fmt.Sprintf("%-38s %s · %s", m.id, m.contextLen, m.pricing)
}
func (m modelItem) Description() string { return m.shortDesc }
func (m modelItem) FilterValue() string { return m.id }

// Fixture values are real, pulled live from https://openrouter.ai/api/v1/models
// during the #195 design review (context/pricing/description all verbatim
// from that response, short-description generated by the agreed
// strip-markdown+cap-at-72-chars transform). gpt-4o's own numbers additionally
// cross-checked against openrouter.ai/openai/gpt-4o.
var fixture = []list.Item{
	modelItem{
		id: "anthropic/claude-opus-5-fast", contextLen: "1M ctx", pricing: "$10/$50 per M tok",
		shortDesc: "Fast-mode variant of Opus 5 - identical capabilities with higher output…",
		fullDesc:  "Fast-mode variant of [Opus 5](https://openrouter.ai/anthropic/claude-opus-5) - identical capabilities with higher output speed at 2x pricing relative to regular Opus 5.\n\nLearn more in Anthropic's docs: https://platform.claude.com/docs/en/build-with-claude/fast-mode",
	},
	modelItem{
		id: "anthropic/claude-opus-5", contextLen: "1M ctx", pricing: "$5.00/$25 per M tok",
		shortDesc: "Claude Opus 5 is Anthropic's flagship model for demanding reasoning,…",
		fullDesc:  "**Claude Opus 5** is Anthropic's flagship model for demanding reasoning, coding, and long-horizon agentic work. It is particularly strong at end-to-end software tasks, code review and bug finding, visual analysis, and multi-step tool use across long sessions.",
	},
	modelItem{
		id: "inclusionai/ling-3.0-flash:free", contextLen: "256k ctx", pricing: "free",
		shortDesc: "Ling-3.0-flash is a 124B-parameter Mixture-of-Experts (MoE) model, with…",
		fullDesc:  "*Ling-3.0-flash* is a *124B-parameter Mixture-of-Experts (MoE) model*, with approximately *5.1B parameters activated per token*. The model is designed with token efficiency and production-scale agentic inference as key priorities, enabling developers to run high-throughput workloads at low serving cost.",
	},
	modelItem{
		id: "poolside/laguna-s-2.1", contextLen: "1M ctx", pricing: "$0.10/$0.20 per M tok",
		shortDesc: "Laguna S 2.1 is the latest coding agent model from Poolside. Laguna S…",
		fullDesc:  "Laguna S 2.1 is the latest coding agent model from [Poolside](https://poolside.ai/). Laguna S 2.1 is a 118B total parameter model with 8B active parameters, scoring 70.2% on Terminal-Bench 2.1 and strong results on other agentic coding benchmarks.",
	},
	modelItem{
		id: "google/gemini-3.6-flash", contextLen: "1M ctx", pricing: "$1.50/$7.50 per M tok",
		shortDesc: "Gemini 3.6 Flash is a high-efficiency model from Google for coding,…",
		fullDesc:  "Gemini 3.6 Flash is a high-efficiency model from Google for coding, agentic workflows, and web and app development. It is designed to produce polished outputs with fewer unnecessary edits and better instruction-following on multi-step tasks.",
	},
	modelItem{
		id: "meituan/longcat-2.0", contextLen: "1M ctx", pricing: "$0.30/$1.20 per M tok",
		shortDesc: "LongCat 2.0 is a sparse mixture-of-experts language model from Meituan,…",
		fullDesc:  "LongCat 2.0 is a sparse mixture-of-experts language model from Meituan, with 48B active parameters out of 1.6T total. It is suited for coding, repository-level changes, long-horizon problem solving, and agentic workflows.",
	},
	modelItem{
		id: "openai/gpt-4o", contextLen: "128k ctx", pricing: "$2.50/$10 per M tok",
		shortDesc: "OpenAI's flagship multimodal model, balancing speed, cost, and…",
		fullDesc:  "OpenAI's flagship multimodal model, balancing speed, cost, and capability across text, vision, and audio. A strong general-purpose default for most chat and agentic workloads.",
	},
}

var (
	reLink       = regexp.MustCompile(`\[([^\]]+)\]\(([^)]+)\)`)
	reEmphasis   = regexp.MustCompile(`\*{1,2}([^*]+)\*{1,2}`)
	htmlEntities = strings.NewReplacer("&lt;", "<", "&gt;", ">", "&amp;", "&")

	markdownishBold = lipgloss.NewStyle().Bold(true)
	markdownishLink = lipgloss.NewStyle().Underline(true).Foreground(lipgloss.Color("39"))
	markdownishDim  = lipgloss.NewStyle().Faint(true)
)

// renderMarkdownish applies basic terminal styling to the small subset of
// markdown OpenRouter descriptions actually use — [text](url) links and
// *single*/**double** asterisk emphasis (the real API data treats both the
// same way in practice; distinguishing bold vs. italic isn't worth the
// regex complexity for a description blurb). Anything else passes through
// as plain text. Order matters: links first, so an emphasis marker can't
// accidentally split a link's brackets/parens; emphasis's inserted ANSI
// escapes contain no asterisks, so it can't double-match its own output.
func renderMarkdownish(s string) string {
	s = reLink.ReplaceAllStringFunc(s, func(match string) string {
		g := reLink.FindStringSubmatch(match)
		return markdownishLink.Render(g[1]) + markdownishDim.Render(" ("+g[2]+")")
	})
	s = reEmphasis.ReplaceAllStringFunc(s, func(match string) string {
		g := reEmphasis.FindStringSubmatch(match)
		return markdownishBold.Render(g[1])
	})
	return htmlEntities.Replace(s)
}

type demoModel struct {
	list       list.Model
	chosen     string // empty means cancelled (esc/ctrl+c) or nothing selected
	detailBox  lipgloss.Style
	detailWrap lipgloss.Style
}

func (m demoModel) Init() tea.Cmd { return nil }

func (m demoModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.KeyMsg:
		switch msg.String() {
		case "enter":
			if it, ok := m.list.SelectedItem().(modelItem); ok {
				m.chosen = it.id
			}
			return m, tea.Quit
		case "ctrl+c", "esc":
			return m, tea.Quit
		}
	case tea.WindowSizeMsg:
		listWidth := msg.Width*3/5 - 1
		detailWidth := msg.Width - listWidth - 5 // border(2) + padding(2) + gap(1)
		m.list.SetWidth(listWidth)
		m.list.SetHeight(msg.Height - 2)
		m.detailBox = m.detailBox.Width(detailWidth).Height(msg.Height - 4).MarginLeft(1)
		m.detailWrap = m.detailWrap.Width(detailWidth - 2) // minus the box's own padding
	}
	var cmd tea.Cmd
	m.list, cmd = m.list.Update(msg)
	return m, cmd
}

// detailPane renders the full, untruncated description of whatever item the
// cursor is currently on — this lives outside list.Model's own View/height
// accounting (bubbles/list's ItemDelegate.Height() is a single fixed value
// applied to every row for its pagination math, confirmed in
// vendor/.../bubbles/list/list.go:38-53, so a row can't grow taller only
// when focused; a separate pane is the only way to show more text on focus
// without wasting that same height on every other row).
func (m demoModel) detailPane() string {
	it, ok := m.list.SelectedItem().(modelItem)
	if !ok {
		return ""
	}
	return m.detailBox.Render(m.detailWrap.Render(renderMarkdownish(it.fullDesc)))
}

func (m demoModel) View() string {
	return lipgloss.JoinHorizontal(lipgloss.Top, m.list.View(), m.detailPane())
}

func main() {
	delegate := list.NewDefaultDelegate()
	l := list.New(fixture, delegate, 100, 20)
	l.Title = "Select an OpenRouter model (/ to filter, enter to confirm, esc to cancel)"
	l.SetShowStatusBar(false)
	l.Styles.Title = lipgloss.NewStyle().Bold(true)

	dm := demoModel{
		list:       l,
		detailBox:  lipgloss.NewStyle().Border(lipgloss.RoundedBorder()).Padding(0, 1).Width(96),
		detailWrap: lipgloss.NewStyle().Width(92),
	}
	p := tea.NewProgram(dm, tea.WithAltScreen())
	m, err := p.Run()
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
	final := m.(demoModel)
	if final.chosen == "" {
		fmt.Println("cancelled")
		return
	}
	fmt.Println("chosen model:", final.chosen)
}
