# home-manager module: `services.tent-backend-lima`.
#
# Manages a darwin Lima VM via a LaunchAgent so `clown --tent` (or any
# downstream consumer) has a containerd-capable VM available at login.
# Lima supports parallel VMs on darwin (unlike podman-machine), so this
# module is the recommended backend for the clown tent dev loop —
# clown#99 spike (zz-pocs/tent-lima/) validated the end-to-end shape.
#
# Why a separate module instead of extending the existing
# (eng-side) podman-darwin module: Lima and podman-machine are
# different VM-lifecycle tools with different yaml schemas and
# different `limactl`/`podman machine` argv. A single module would
# leak both surfaces. Downstream consumers (eng) can adopt this
# module alongside or instead of programs.podman-darwin; clown's
# own dev-tent-machine-* flake apps continue to target podman-
# machine until a future migration switches them over.
#
# Why darwin-only: Lima's value proposition (a hypervisor wrapper) is
# only relevant on darwin (and windows). On linux, containers run on
# the host directly. The module rejects activation on linux with a
# clear error rather than silently no-op'ing.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib)
    mkEnableOption
    mkIf
    mkOption
    types
    concatStringsSep
    optional
    optionalAttrs
    ;

  cfg = config.services.tent-backend-lima;

  # Render the mount list as a yaml fragment. Each mount is:
  #   - location: "<host-path>"
  #     writable: <bool>
  # `mountPoint` is intentionally NOT set: Lima auto-resolves it,
  # and explicitly setting `mountPoint = $HOME` triggers Lima's
  # "reserved internal home directory" rejection (zz-pocs/tent-lima
  # gotcha #1). Override individually via mountPoint if needed.
  renderMount =
    m:
    let
      mp = lib.optionalString (m.mountPoint != null) ''
        mountPoint: ${builtins.toJSON m.mountPoint}
      '';
    in
    ''
      - location: ${builtins.toJSON m.location}
        ${mp}writable: ${if m.writable then "true" else "false"}
    '';

  mountsYaml = concatStringsSep "" (map renderMount cfg.mounts);

  # Full yaml content. Built from options so the module is the
  # single source of truth — no user-supplied yaml file to keep
  # in sync.
  yamlContent = ''
    # Generated by services.tent-backend-lima. Do not edit by hand;
    # the module recreates the VM on mount-list / size changes.
    vmType: vz
    mountType: virtiofs
    cpus: ${toString cfg.cpus}
    memory: ${cfg.memory}
    disk: ${cfg.disk}

    images:
    - location: ${builtins.toJSON cfg.imageUrl}
      arch: ${cfg.imageArch}

    mounts:
    ${mountsYaml}
    ssh:
      forwardAgent: ${if cfg.forwardAgent then "true" else "false"}

    containerd:
      system: true
      user: true
  '';

  yamlFile = pkgs.writeText "tent-backend-lima-${cfg.machineName}.yaml" yamlContent;

  # Hash of the rendered yaml. On activation, the launcher compares
  # this against a stored sentinel; mismatch triggers a destroy+
  # recreate of the VM. Mirrors the eng#111-shaped drift-detection
  # that clown#99 surfaced as a needed feature.
  yamlHash = builtins.hashString "sha256" yamlContent;

  binPath = "${cfg.package}/bin/limactl";

  # Launch script. Idempotent across re-runs:
  # - If the VM doesn't exist, `limactl create` from the rendered yaml.
  # - If it exists but the sentinel hash differs (yaml drift), destroy
  #   and recreate.
  # - Start it if not running.
  launcher = pkgs.writeShellScript "tent-backend-lima-launch" ''
    set -eu
    : "''${HOME:?HOME must be set}"
    : "''${XDG_STATE_HOME:=$HOME/.local/state}"
    : "''${XDG_LOG_HOME:=$HOME/.local/log}"

    NAME=${lib.escapeShellArg cfg.machineName}
    YAML=${lib.escapeShellArg yamlFile}
    DESIRED_HASH=${lib.escapeShellArg yamlHash}
    LIMACTL=${lib.escapeShellArg binPath}
    SENTINEL_DIR="$XDG_STATE_HOME/tent-backend-lima"
    SENTINEL_FILE="$SENTINEL_DIR/$NAME.hash"

    mkdir -p -m 0700 "$SENTINEL_DIR"
    mkdir -p -m 0755 "$XDG_LOG_HOME"

    # 1. Drift check: if the machine exists and the stored hash
    #    differs from the desired hash, blow it away and recreate.
    #    First-run case: sentinel doesn't exist; treat as drift and
    #    create the machine.
    if "$LIMACTL" list --json 2>/dev/null | grep -q "\"name\":\"$NAME\""; then
      stored_hash=""
      if [ -f "$SENTINEL_FILE" ]; then
        stored_hash="$(cat "$SENTINEL_FILE")"
      fi
      if [ "$stored_hash" != "$DESIRED_HASH" ]; then
        echo ">> tent-backend-lima: config drift detected; recreating $NAME" >&2
        "$LIMACTL" stop "$NAME" >/dev/null 2>&1 || true
        "$LIMACTL" delete --force "$NAME"
      fi
    fi

    # 2. Create if missing.
    if ! "$LIMACTL" list --json 2>/dev/null | grep -q "\"name\":\"$NAME\""; then
      echo ">> tent-backend-lima: creating $NAME" >&2
      "$LIMACTL" create --name="$NAME" --tty=false "$YAML"
      printf '%s' "$DESIRED_HASH" > "$SENTINEL_FILE"
    fi

    # 3. Start if not running.
    state="$("$LIMACTL" list --json 2>/dev/null \
      | grep "\"name\":\"$NAME\"" \
      | sed -E 's/.*"status":"([^"]+)".*/\1/' \
      || echo unknown)"
    if [ "$state" != "Running" ]; then
      echo ">> tent-backend-lima: starting $NAME (state was $state)" >&2
      exec "$LIMACTL" start --tty=false "$NAME"
    fi
    echo ">> tent-backend-lima: $NAME already running"
  '';

in
{
  options.services.tent-backend-lima = {
    enable = mkEnableOption "Lima VM for clown --tent (darwin only)";

    package = mkOption {
      type = types.package;
      default = pkgs.lima;
      defaultText = lib.literalExpression "pkgs.lima";
      description = ''
        Lima package providing `limactl`. Defaults to nixpkgs `lima`.
      '';
    };

    machineName = mkOption {
      type = types.str;
      default = "clown-tent";
      description = ''
        Lima instance name. Must be a valid Lima machine name (lower-case,
        alphanumeric + hyphens). Used as both the instance name and as
        the `--connection`/context name from container CLIs.
      '';
    };

    cpus = mkOption {
      type = types.ints.positive;
      default = 6;
      description = "CPUs allocated to the VM.";
    };

    memory = mkOption {
      type = types.str;
      default = "4GiB";
      description = "Memory allocated to the VM (Lima yaml format, e.g. '4GiB').";
    };

    disk = mkOption {
      type = types.str;
      default = "100GiB";
      description = "Disk size for the VM (Lima yaml format, e.g. '100GiB').";
    };

    imageUrl = mkOption {
      type = types.str;
      default = "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img";
      description = ''
        URL of the cloud image to boot the VM from. Defaults to the
        Ubuntu 24.04 aarch64 cloud image used by zz-pocs/tent-lima.
      '';
    };

    imageArch = mkOption {
      type = types.enum [
        "aarch64"
        "x86_64"
      ];
      default = "aarch64";
      description = "CPU architecture of the cloud image (aarch64 or x86_64).";
    };

    forwardAgent = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Forward the host's SSH agent into the VM via Lima's
        `ssh.forwardAgent`. The agent socket is published at
        `/run/host-services/ssh-auth.sock` inside the VM (Docker
        Desktop / OrbStack / Lima convention). Containers can
        bind-mount that path with `-v /run/host-services/ssh-auth.sock
        :/run/host-services/ssh-auth.sock` to gain agent access.
      '';
    };

    mounts = mkOption {
      type = types.listOf (
        types.submodule {
          options = {
            location = mkOption {
              type = types.str;
              description = "Host path to mount into the VM.";
            };
            mountPoint = mkOption {
              type = types.nullOr types.str;
              default = null;
              description = ''
                In-VM mount point. Default null lets Lima resolve it
                automatically (recommended for the home mount — see
                gotcha #1 in zz-pocs/tent-lima/README.md).
              '';
            };
            writable = mkOption {
              type = types.bool;
              default = false;
              description = "Whether the mount is writable inside the VM.";
            };
          };
        }
      );
      default = [
        {
          location = "/nix/store";
          mountPoint = "/nix/store";
          writable = false;
        }
        {
          location = "/nix/var";
          mountPoint = "/nix/var";
          writable = true;
        }
        {
          location = "/etc/nix";
          mountPoint = "/etc/nix";
          writable = false;
        }
        {
          location = "{{.Home}}";
          # mountPoint omitted — Lima auto-resolves; setting it to
          # $HOME explicitly triggers the "reserved internal home
          # directory" rejection.
          mountPoint = null;
          writable = true;
        }
      ];
      description = ''
        Mount list for the Lima VM. Default matches the mount set
        clown's `--tent` flow expects (the same paths the eng-side
        `programs.podman-darwin` module exposes). Override to add
        project-specific mounts.
      '';
    };
  };

  config = mkIf cfg.enable (
    lib.mkMerge [
      {
        # Make the lima binary available on PATH. Downstream tooling
        # (clown's dev-tent-machine-* recipes) currently looks for
        # limactl on PATH.
        home.packages = [ cfg.package ];

        # Fail loudly on linux. Lima exists for linux too, but the
        # value proposition (a hypervisor wrapper) doesn't apply: on
        # linux the host IS linux, and containers run natively without
        # a VM. Use rootless podman or docker directly. The module
        # rejects linux activation rather than silently no-op'ing.
        assertions = [
          {
            assertion = pkgs.stdenv.isDarwin;
            message = ''
              services.tent-backend-lima.enable is only meaningful on
              darwin. On linux, run containers directly via rootless
              podman/docker — no VM wrapper is needed.
            '';
          }
        ];
      }

      # Darwin: launchd agent that runs the launcher at login. Like
      # ringmaster, KeepAlive { Crashed = true } restarts on crash
      # but lets clean exits stick.
      (mkIf pkgs.stdenv.isDarwin {
        launchd.agents.tent-backend-lima = {
          enable = true;
          config = {
            Label = "com.amarbel-llc.tent-backend-lima";
            ProgramArguments = [ "${launcher}" ];
            EnvironmentVariables = {
              # Burn the launcher derivation path into the plist's
              # env so home-manager activation re-renders the plist
              # whenever the launcher changes (driving an automatic
              # `launchctl bootout && bootstrap` cycle).
              _TENT_BACKEND_LIMA_LAUNCH = "${launcher}";
            };
            KeepAlive = {
              # `limactl start` exits 0 after the VM is up; we don't
              # want launchd to restart it. KeepAlive on crash only.
              Crashed = true;
              SuccessfulExit = false;
            };
            RunAtLoad = true;
            ProcessType = "Background";
            AbandonProcessGroup = true;
            StandardOutPath = "${config.home.homeDirectory}/.local/log/tent-backend-lima.log";
            StandardErrorPath = "${config.home.homeDirectory}/.local/log/tent-backend-lima.log";
          };
        };
      })
    ]
  );
}
