# Tab completion for clown-codex

# Top-level commands
complete -c clown-codex -f -n __fish_use_subcommand -a exec -d 'Run Codex non-interactively'
complete -c clown-codex -f -n __fish_use_subcommand -a review -d 'Run a code review non-interactively'
complete -c clown-codex -f -n __fish_use_subcommand -a login -d 'Manage login'
complete -c clown-codex -f -n __fish_use_subcommand -a logout -d 'Remove stored authentication credentials'
complete -c clown-codex -f -n __fish_use_subcommand -a mcp -d 'Manage external MCP servers for Codex'
complete -c clown-codex -f -n __fish_use_subcommand -a resume -d 'Resume a previous interactive session'
complete -c clown-codex -f -n __fish_use_subcommand -a fork -d 'Fork a previous interactive session'
complete -c clown-codex -f -n __fish_use_subcommand -a completion -d 'Generate shell completion scripts'
complete -c clown-codex -f -n __fish_use_subcommand -a help -d 'Print help'

# Shared options
complete -c clown-codex -x -n __fish_use_subcommand -s c -l config -d 'Override a configuration value'
complete -c clown-codex -x -n __fish_use_subcommand -l enable -d 'Enable a feature'
complete -c clown-codex -x -n __fish_use_subcommand -l disable -d 'Disable a feature'
complete -c clown-codex -x -n __fish_use_subcommand -l remote -d 'Connect to a remote app server'
complete -c clown-codex -x -n __fish_use_subcommand -l remote-auth-token-env -d 'Bearer token env var for remote mode'
complete -c clown-codex -x -n __fish_use_subcommand -s i -l image -d 'Attach image files'
complete -c clown-codex -x -n __fish_use_subcommand -s m -l model -d 'Model to use'
complete -c clown-codex -f -n __fish_use_subcommand -l oss -d 'Use the local OSS model provider'
complete -c clown-codex -x -n __fish_use_subcommand -l local-provider -d 'Select the local provider'
complete -c clown-codex -x -n __fish_use_subcommand -s p -l profile -d 'Configuration profile'
complete -c clown-codex -x -n __fish_use_subcommand -s s -l sandbox -a 'read-only workspace-write danger-full-access' -d 'Sandbox mode'
complete -c clown-codex -x -n __fish_use_subcommand -s a -l ask-for-approval -a 'untrusted on-failure on-request never' -d 'Approval policy'
complete -c clown-codex -f -n __fish_use_subcommand -l full-auto -d 'Run with workspace-write and on-request approvals'
complete -c clown-codex -f -n __fish_use_subcommand -l dangerously-bypass-approvals-and-sandbox -d 'Disable sandbox and approvals'
complete -c clown-codex -x -n __fish_use_subcommand -s C -l cd -d 'Working directory'
complete -c clown-codex -f -n __fish_use_subcommand -l search -d 'Enable live web search'
complete -c clown-codex -x -n __fish_use_subcommand -l add-dir -d 'Additional writable directories'
complete -c clown-codex -f -n __fish_use_subcommand -l no-alt-screen -d 'Disable alternate screen mode'
complete -c clown-codex -f -n __fish_use_subcommand -s h -l help -d 'Display help'
complete -c clown-codex -f -n __fish_use_subcommand -s V -l version -d 'Display version'

# Resume and fork subcommands
complete -c clown-codex -x -n '__fish_seen_subcommand_from resume' -a '(clown-codex-sessions 2>/dev/null)' -d 'Resume a Codex session'
complete -c clown-codex -f -n '__fish_seen_subcommand_from resume' -l last -d 'Resume the most recent session'
complete -c clown-codex -f -n '__fish_seen_subcommand_from resume' -l all -d 'Show all sessions'
complete -c clown-codex -f -n '__fish_seen_subcommand_from resume' -l include-non-interactive -d 'Include non-interactive sessions'
complete -c clown-codex -x -n '__fish_seen_subcommand_from fork' -a '(clown-codex-sessions 2>/dev/null)' -d 'Fork a Codex session'
complete -c clown-codex -f -n '__fish_seen_subcommand_from fork' -l last -d 'Fork the most recent session'
complete -c clown-codex -f -n '__fish_seen_subcommand_from fork' -l all -d 'Show all sessions'
complete -c clown-codex -f -n '__fish_seen_subcommand_from fork' -l include-non-interactive -d 'Include non-interactive sessions'
